version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10.

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - store_test_results:
          path: test_reports
      - store_artifacts:
          path: test_reports

workflows:
  heroku_deploy:
    jobs:
      - build-and-test
      - heroku/deploy-via-git: # preconfigured job
          requires: 
            - build-and-test
          filters:
            branches:
              only: master
  pr-check:
    jobs:
      - build-and-test:
          context: spoonacular-apis 
          filters:
            branches:
              ignore:
                - master